- CHANGELOG
- build/pupmod-simp-compliance_markup.spec
- metadata.json
> (SIMP-1576) Change origin to `github.com/simp`

- .travis.yml
- CHANGELOG
- metadata.json
- version was not updated since last release and changes were made
- updated travis.yml file
SIMP-2865  #close
SIMP-2748  #comment compliance_markup bumped
> (SIMP-2748) Bumped version for RC release

- .gitlab-ci.yml
> (SIMP-3191) add gitlabci to simp module

- CHANGELOG
- README.md
- metadata.json
The report format, without documentation, isn't really all that useful
SIMP-3310 #close
> (SIMP-3310) Documented the report format

- CHANGELOG
> (SIMP-3452) compliance_markup - malformed changelog entry

- .travis.yml
- CHANGELOG
- metadata.json
Prep for tag and release
SIMP-3685 #comment pupmod-simp-compliance_markup RPM prep
> (SIMP-3685) pupmod-simp-compliance_markup - Fix version

- CHANGELOG
Fix typos in CHANGELOG
SIMP-3969 #comment compliance_markup cleanup
> (SIMP-3969) compliance_markup - CHANGELOG cleanup

- CHANGELOG
- data/compliance_profiles/CentOS/6/nist_800_53_rev4.json
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/CentOS/7/nist_800_53_rev4.json
- data/compliance_profiles/RedHat/6/nist_800_53_rev4.json
- data/compliance_profiles/RedHat/7/disa_stig.json
- data/compliance_profiles/RedHat/7/nist_800_53_rev4.json
- metadata.json
- Better align with the latest SSG EL7 STIG content
- Fixed several incorrectly typed parameters
SIMP-4054 #close
> (SIMP-4054) Align with the latest SSG STIG content

- CHANGELOG
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
- Added new variables and settings to disa stig profiles for
el7
SIMP-4688 #comment updated compliance profile
SIMP-4789 #close   Compliance module changes
SIMP-4870 #close
added protocol setting
> (SIMP-4688) STIG sshd configuration updates

- CHANGELOG
- data/compliance_profiles/CentOS/6/nist_800_53_rev4.json
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/CentOS/7/nist_800_53_rev4.json
- data/compliance_profiles/RedHat/6/nist_800_53_rev4.json
- data/compliance_profiles/RedHat/7/disa_stig.json
- data/compliance_profiles/RedHat/7/nist_800_53_rev4.json
- Replaced OBE simp::yum::enable_auto_updates entries with
simp::yum::schedule::enable in all profiles
- Added and updated simp::yum::schedules entries for DISA STIG
SIMP-4719 #close
> (SIMP-4719) Map simp::yum::schedule::enable to STIG profile

- CHANGELOG
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
> (SIMP-4734) Add aide::aliases entries to DISA STIG profiles

- CHANGELOG
- Gemfile
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
- added settings if main.cf  for RHEL-07-040680
SIMP-4703 #comment updated compliance module.
> (SIMP-4703) DISA STIG updates for postfix

- CHANGELOG
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
SIMP-4757 #comment pupmod-simp-compliance_markup update for selinux command monitoring
> (SIMP-4757) Add auditd param for monitoring selinux commands

- CHANGELOG
- Gemfile
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
> (SIMP-4763) Add auditd::config::audit_profiles::simp::audit_sudoers to STIG profiles

- .gitlab-ci.yml
- .travis.yml
- CHANGELOG
- Gemfile
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
> (SIMP-4755)  Add auditd::action_mail_acct to STIG profile

- CHANGELOG
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
> (SIMP-4657) Update STIG items for GDM and GNOME

- CHANGELOG
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/RedHat/7/disa_stig.json
> (SIMP-4696) Added selinux::login_resources to STIG

- CHANGELOG
- data/compliance_profiles/CentOS/6/nist_800_53_rev4.json
- data/compliance_profiles/CentOS/7/disa_stig.json
- data/compliance_profiles/CentOS/7/nist_800_53_rev4.json
- data/compliance_profiles/OracleLinux/6/nist_800_53_rev4.json
- data/compliance_profiles/OracleLinux/7/disa_stig.json
- data/compliance_profiles/OracleLinux/7/nist_800_53_rev4.json
- data/compliance_profiles/RedHat/6/nist_800_53_rev4.json
- data/compliance_profiles/RedHat/7/disa_stig.json
- data/compliance_profiles/RedHat/7/nist_800_53_rev4.json
Tlog is a maintained and supported logging shell that we are using to
replace 'sudosh'
> (SIMP-5099) Migration to 'tlog' from 'sudosh'

- CHANGELOG
- metadata.json
SIMP-6229 #comment pupmod-simp-compliance_markup
> (SIMP-6229) Update upper bound stdlib < 6.0.0

- CHANGELOG
- lib/puppetx/simp/compliance_mapper.rb
> (SIMP-6239) Fix bug in Array merging

- spec/classes/init_spec.rb
Added some additional tests to ensure that the summary content was
working properly.
> (SIMP-MAINT) Test updates

- CHANGELOG
- lib/puppet/parser/functions/compliance_map.rb
- lib/puppetx/simp/compliance_mapper.rb
- metadata.json
- Update confinement logic to ensure that all possibilities are collected
- Add debugging logs to enforcement logic
- Raise errors on malformed data
SIMP-6972 #close
> (SIMP-6972) Confinement logic update

- CHANGELOG
- lib/puppet/functions/compliance_markup/enforcement.rb
- lib/puppetx/simp/compliance_mapper.rb
Ensure that the Hiera backend recurses as little as possible to improve
performance.
Also fixed a bug in the backend where the legacy v1 information was not
being properly cached.
SIMP-5933 #close
> (SIMP-5933) Performance Improvements

- CHANGELOG
- lib/puppetx/simp/compliance_mapper.rb
- metadata.json
- spec/classes/init_spec.rb
> (SIMP-8229) Add controls, identifiers, and oval-ids

- CHANGELOG
- lib/puppetx/simp/compliance_mapper.rb
- metadata.json
Moves evaluation of hieradata after file imports.
SIMP-8448 #close
> (SIMP-8448) Allow profile overrides via hiera

- CHANGELOG
- lib/puppet/functions/compliance_markup/enforcement.rb
- lib/puppetx/simp/compliance_map.rb
- lib/puppetx/simp/compliance_mapper.rb
- spec/functions/compliance_markup/05_enforcement_override_spec.rb
[SIMP-9623] #close
[SIMP-9623]: https://simp-project.atlassian.net/browse/SIMP-9623
> (SIMP-9623) Disable caching across calls to compliance_markup::enforcement

- CHANGELOG
- lib/puppet/functions/compliance_markup/enforcement.rb
- lib/puppetx/simp/compliance_mapper.rb
- metadata.json
- spec/acceptance/nodesets/docker_oel.yml
- spec/acceptance/nodesets/oel.yml
> (SIMP-9646) Fix recursion issues

- CHANGELOG
- lib/puppetx/simp/compliance_mapper.rb
- spec/fixtures/hieradata/disa_spec.yaml
- spec/fixtures/hieradata/nist_spec.yaml
- spec/functions/compliance_markup/10_enforce_spec.rb
Fixed:
* Cast the lookup for 'compliance_markup::enforcement' to an Array to prevent
hangs
SIMP-8138 #close
> SIMP-8138 - Fix issue with String profile

- CHANGELOG
- README.md
- lib/puppetx/simp/compliance_mapper.rb
- metadata.json
- spec/functions/compliance_markup/06_enforcement_debug_spec.rb
Add `compliance_markup::debug::profiles` key that lists available profiles
SIMP-9785 #close
> (SIMP-9785) Add debug key to list available profiles

- .gitlab-ci.yml
- CHANGELOG
- REFERENCE.md
- metadata.json
- spec/acceptance/nodesets/amzn2.yml
- spec/spec_helper_acceptance.rb
> Support Amazon Linux 2

- .gitlab-ci.yml
- CHANGELOG
- lib/puppet/functions/compliance_markup/enforcement.rb
- spec/functions/compliance_markup/03_enforcement_profile_merge_spec.rb
> Reproducer for fixing the knockout prefix bug

- .gitignore
- CHANGELOG
- lib/puppetx/simp/compliance_map.rb
- metadata.json
- spec/classes/init_spec.rb
- spec/fixtures/hieradata/escaped_knockout/SIMP/compliance_profiles/escaped_knockout.yaml
> (#150) Updated reporting to account for escaped dashes

- CHANGELOG
- lib/puppetx/simp/compliance_map.rb
- metadata.json
- spec/classes/init_spec.rb
* Fixes for Ruby 3
* Add explicit support for Puppet 8
* Drop support for Puppet 6
* Add support for stdlib 9
Fixes #163
> Updates for Puppet 8

- .github/workflows/pr_tests.yml
- .rubocop.yml
- CHANGELOG
- Gemfile
- lib/puppet/functions/compliance_markup/compliance_map.rb
- lib/puppet/functions/compliance_markup/enforcement.rb
- lib/puppet/functions/compliance_markup/loaded_maps.rb
- lib/puppetx/simp/compliance_map.rb
- lib/puppetx/simp/compliance_mapper.rb
- metadata.json
- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/default/10_enforce_spec.rb
- spec/classes/init_spec.rb
- spec/functions/compliance_markup/00_enforcement_spec.rb
- spec/functions/compliance_markup/01_enforcement_confine_spec.rb
- spec/functions/compliance_markup/02_enforcement_merge_spec.rb
- spec/functions/compliance_markup/03_enforcement_profile_merge_spec.rb
- spec/functions/compliance_markup/04_enforcement_profile_merge_spec.rb
- spec/functions/compliance_markup/05_enforcement_override_spec.rb
- spec/functions/compliance_markup/06_enforcement_debug_spec.rb
- spec/functions/compliance_markup/10_enforce_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/unit/compliance_engine/compliance_engine_enforce_spec.rb
- utils/compliance_map_migrate
- utils/compliance_profile_json2yaml.rb
- utils/compliance_profile_yaml2json.rb
- utils/import_from_v1.rb
- utils/v1_to_v2/merge_el6_el7.rb
* Add .rubocop.yml
* Clean up GHA workflows and enable rubocop
* Refactor rspec tests to avoid writing to the filesystem where possible
* Fix use of legacy facts
> Cleanup for rubocop
