simp/pupmod-simp-compliance_markup

lib/puppet/parser/functions/compliance_map.rb, lib/puppetx/simp/compliance_map.rb, spec/classes/init_spec.rb
The compliance_map function would fail if there was no compliance_map
Hash available in the lookup sources.
This outputs a proper error instead of just crashing.
SIMP-1866 #close
=> (SIMP-1866) Catch errors if no compliance_map

.gitignore, .travis.yml, CHANGELOG, Gemfile, lib/puppet/parser/functions/compliance_map.rb, lib/puppetx/compliance/compliance_markup/v1/test.yaml, lib/puppetx/simp/compliance_map.rb, lib/puppetx/simp/compliance_mapper.rb, manifests/test.pp, metadata.json, spec/acceptance/nodesets/docker.yml, spec/acceptance/suites/default/00_default_spec.rb, spec/classes/init_spec.rb, spec/classes/test_spec.rb, spec/functions/compliance_map_spec.rb, tests/data/common.yaml, tests/hiera.yaml, tests/test.pp
Replace the compliance mapper's report generator parsing code
with the shared library used by the enforcement backend. This
means that the code to read and parse v1 format compliance maps
is now centralized.
Add vendored (maps-in-modules) support to the compiler for v1
format maps. Note: the operation of this is not well defined, and
intended for use in the v2 format of the compliance maps.
Also expand the shared library to a real object tree, with defined
api endpoints, like load() to load a set of compliance maps, and
list_puppet_params() to generate a puppet parameter hash.
Note: this code was tested using the existing spec tests without
modifications to ensure that the change is a drop-in replacement.
The code coverage of the tests may not be complete to do this.
SIMP-3784 #close
=> (SIMP-3784) Replace the compliance mapper's report generator

CHANGELOG, data/compliance_profiles/CentOS/6/nist_800_53_rev4.json, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/CentOS/7/nist_800_53_rev4.json, data/compliance_profiles/RedHat/6/nist_800_53_rev4.json, data/compliance_profiles/RedHat/7/disa_stig.json, data/compliance_profiles/RedHat/7/nist_800_53_rev4.json, metadata.json
The DISA and NIST compliance profiles had conflicting values for
puppet parameters. After re-reviewing we found that all the values
should be the same on both NIST and DISA profiles.
This updates the data to match
SIMP-3840 #close
=> (SIMP-3840) Fix discrepencies between nist and disa compliance profiles

.gitlab-ci.yml, .puppet-lint.rc, .travis.yml, CHANGELOG, Gemfile, data/compliance_profiles/CentOS/6/nist_800_53_rev4.json, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/CentOS/7/nist_800_53_rev4.json, data/compliance_profiles/RedHat/6/nist_800_53_rev4.json, data/compliance_profiles/RedHat/7/disa_stig.json, data/compliance_profiles/RedHat/7/nist_800_53_rev4.json, metadata.json
- Consolidated duplicate entries for useradd::etc_profile::session_timeout
and pam::fail_interval on CentOS7 disa_stig.json
- Copied over more current CentOS7 disa_stig.json to RedHat7.
This fixed the TMOUT setting problem.
- Added missing audispd program to simp_rsyslog::default_logs
- Added missing ' IPT:' message start to simp_ryslog::default_logs.
This is required for iptables violation messages because some
versions of rsyslog add a space separating the message
timestamp/id and the message.
- Fixed unnecessary version bump for an unreleased change.
SIMP-4421 #close
=> (SIMP-4421) TMOUT setting does not match STIG for EL7

CHANGELOG, lib/puppetx/simp/compliance_map.rb, lib/puppetx/simp/compliance_mapper.rb, metadata.json, spec/classes/init_spec.rb, spec/classes/test_spec.rb, spec/fixtures/hieradata/passing_checks.yaml, spec/fixtures/hieradata/test1_deviation.yaml
* Fixed issues with the compliance_map logic that were causing false
results to be added to the 'documented_missing_parameters' and
'documented_missing_resources' lists
* Added tests to catch regressions in the future
* Added a timestamp to the report output
SIMP-4317 #comment fix compliance_map logic
=> (SIMP-4639) Fix compliance_map logic

CHANGELOG, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json
Value now set to 0.
SIMP-4840 #close
SIMP-4841 #close
=> (SIMP-4840) Fix useradd::useradd::inactive in DISA STIG profiles

CHANGELOG, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json
Added simp::sysctl entries to the DISA STIG profiles for
net.ipv4.conf.default.accept_source_route,
net.ipv4.conf.default.send_redirects, and
net.ipv6.conf.all.accept_source_route.
SIMP-4725 #close
=> (SIMP-4725) Update simp::systctl values in compliance maps

.gitlab-ci.yml, CHANGELOG, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json
DISA STIG profile updates:
- Added auditd::failure_mode entries
- Corrected auditd::enable identifiers
SIMP-4769 #close
=> (SIMP-4769) Set auditd failure mode to 2 for STIG

.gitlab-ci.yml, .travis.yml, CHANGELOG, Gemfile, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json, spec/acceptance/suites/default/00_default_spec.rb
This adds `auditd::config::audit_profiles::simp::audit_session_files`
and `auditd::config::audit_profiles::simp::audit_session_files_tag`
to the EL7 STIG mappings.
Note that `auditd::...::simp::audit_session_files` governs audit rules
for four files:
- /var/run/utmp
- /var/log/btmp
- /var/log/wtmp
- /var/log/tallylog
However, the only STIG finding that deals with these files is
[V-72143, version RHEL-07-030600][0], which only recommends checking
`/var/log/tallylog` on RHEL7:
> Verify the operating system generates audit records when
> successful/unsuccessful account access count events occur.
>
> Check the file system rule in "/etc/audit/audit.rules" with the
> following commands:
>
> # grep -i /var/log/tallylog /etc/audit/audit.rules
>
> -w /var/log/tallylog -p wa -k logins
>
> If the …
=> (SIMP-4760) Add `audit_session_files` to STIG maps

CHANGELOG, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json
Add data to the DIS STIG items:
- Added auditd::config::audit_profiles::simp::audit_crontab_cmd
- Added auditd::config::audit_profiles::simp::audit_pam_timestamp_check_cmd
- Added auditd::config::audit_profiles::simp::audit_passwd_cmds
- Added auditd::config::audit_profiles::simp::audit_postfix_cmds
- Added auditd::config::audit_profiles::simp::audit_priv_cmds
- Added auditd::config::audit_profiles::simp::audit_ssh_keysign_cmd
SIMP-4952 #close
=> (SIMP-4952) Add map data for recent auditd changes

CHANGELOG, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json
Set the auditd DISA STIG settings for auditd version
8.0.0, the version that introduces the 'stig' audit
profile and allows for sets of audit profiles.
- This is **not** backward compatible with auditd 7.x.
- Updated SRG and STIG IDs
- Did did not validate or add missing OVAL IDs.
SIMP-4679 #comment update compliance_markup
=> (SIMP-4679) Update to settings for auditd 8.0.0

CHANGELOG, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/OracleLinux/7/disa_stig.json, data/compliance_profiles/RedHat/7/disa_stig.json, metadata.json
Fixed the following incorrect parameter types that were found
when getting the simp-core tests to work for SIMP 6.3.0:
- simp::\yum::schedule::minute
- simp::\yum::schedule::hour
SIMP-5490 #comment Fix compliance_markup mapping bugs
=> (SIMP-5490) Fix incorrect parameter types simp::yum::schedule

CHANGELOG, utils/compliance_map_migrate
`utils/compliance_map_migrate` contained an errant `to_yaml` which
caused incorrect output.
SIMP-5525 #comment utils/compliance_map_migrate should be usable with this change.
=> (SIMP-5525) Fix compliance_map_migrate output

CHANGELOG, data/compliance_profiles/CentOS/6/nist_800_53_rev4.json, data/compliance_profiles/CentOS/7/nist_800_53_rev4.json, data/compliance_profiles/OracleLinux/6/nist_800_53_rev4.json, data/compliance_profiles/OracleLinux/7/nist_800_53_rev4.json, data/compliance_profiles/RedHat/6/nist_800_53_rev4.json, data/compliance_profiles/RedHat/7/nist_800_53_rev4.json
Several keys in the v1 compliance_markup data were missing a ':'
separator.  They are corrected with this change.
SIMP-5663 #close
=> (SIMP-5663) Fix errors in v1 compliance_markup data

.gitlab-ci.yml, .travis.yml, Gemfile, spec/acceptance/suites/default/10_enforce_spec.rb, spec/functions/compliance_markup/hiera_backend_spec.rb
- Remove OBE test logic WRT to Puppet version.  The versions
of Puppet allowed by the metadata.json satisfy the original
constraints.
- Skip test that requires other work to handle the incomplete
LookupContext available in rspec'
- Normalize static assets
SIMP-5711 #close
=> (SIMP-5711) compliance_markup acceptance tests fail

.gitlab-ci.yml, Gemfile, rakelib/syntax.rake
This patch fixes a `.gitlab-ci.yml` bug that was posioning the GitLab
Runners' RubyGems cache.  The `pup4` YAML anchor must use `image:
'ruby:2.1'` instead of `image: 'ruby:2.4'`.
Note: This commit is part of a common asset update, and adjusts other
aspects of the `.gitlab-ci.yml` file in order to bring it in line with a
standardized pipeline.  In particular, PE 2017.3 was recently
deprecated, removing Puppet 5.3 from the test matrix of most modules.
SIMP-5987 #close
SIMP-5754 #comment updated pupmod-simp-compliance_markup
=>  (SIMP-5754) Fix `pup_4` Gitlab CI cache poisoning

CHANGELOG, metadata.json, utils/compliance_map_migrate, utils/v1_to_v2/convert_all.sh, utils/v1_to_v2/merge_el6_el7.rb
* Merge values from multiple input files.
* Make 'check_header' consistent with other v2 data.
* Reorder output to match other v2 data.
* Fix controls, oval-ids, and identifiers output.
* Normalize identifier strings.
* Add option to supply confinement.
* Use a strange YAML incantation to avoid anchors in the output.
* Add option to append a string to the checks key.
* Add additional helper scripts for v1 to v2 migration.
SIMP-5525 #comment Improve compliance_map_migrate
=> (SIMP-5525) compliance_map_migrate improvements

.gitlab-ci.yml, .travis.yml, CHANGELOG, Gemfile, lib/puppet/parser/functions/compliance_map.rb, metadata.json
The compliance_map puppet function was failing in Puppet 6. Fixed this
and updated tests to run Puppet 6 testing by default.
SIMP-6676 #close
=> (SIMP-6676) Fix Puppet 6 support

CHANGELOG, lib/puppetx/simp/compliance_map.rb
The percent compliant should always be reported correctly regardless of
the report type being generated.
SIMP-6685 #close
=> (SIMP-6685) Fix percent compliant in summary

CHANGELOG, data/compliance_profiles/CentOS/6/nist_800_53_rev4.json, data/compliance_profiles/CentOS/7/disa_stig.json, data/compliance_profiles/CentOS/7/nist_800_53_rev4.json, data/compliance_profiles/OracleLinux/6/nist_800_53_rev4.json, data/compliance_profiles/OracleLinux/7/disa_stig.json, data/compliance_profiles/OracleLinux/7/nist_800_53_rev4.json, data/compliance_profiles/RedHat/6/nist_800_53_rev4.json, data/compliance_profiles/RedHat/7/disa_stig.json, data/compliance_profiles/RedHat/7/nist_800_53_rev4.json, lib/puppet/parser/functions/compliance_map.rb, lib/puppetx/simp/compliance_mapper.rb, metadata.json
* simp::sssd::client::ldap_domain never should have been managed by the
compliance enforcement data because there is no guarantee that the
system will be connected to LDAP.
* Fixed a bug where `__dir__` was causing issues with some versions of
the puppetserver
* Added a warning statement if the Hiera backend hits an invalid JSON or
YAML file.
SIMP-6674 #close
=> (SIMP-6674) Remove simp::sssd::client::ldap_domain

CHANGELOG, lib/puppet/parser/functions/compliance_map.rb, lib/puppetx/simp/compliance_map.rb, spec/classes/init_spec.rb
- Make the 'timestamp' in the client-side report optional to prevent puppet
from triggering file resource changes every time
SIMP-6869 #close
=> (SIMP-6869) No timestamps in client reports

CHANGELOG, metadata.json, spec/acceptance/nodesets/docker_centos.yml, spec/acceptance/nodesets/docker_oel.yml
I'm getting an "unsatisfied dependencies" warning with the `compliance_markup` module.  I'm hoping this will resolve it.
=> (SIMP-6921) Allow puppetlabs/stdlib 6.x.

.fixtures.yml, CHANGELOG, lib/puppet/functions/compliance_markup/enforcement.rb, lib/puppetx/simp/compliance_map.rb, lib/puppetx/simp/compliance_mapper.rb
This adds two additional features to `confine` blocks:
1. Structured facts (as dotted names, such as `os.family`)
2. Multiple options for facts as an array
For example, to confine a check to EL7 and EL8, with this change we can add a block like this:
```
confine:
os.family: RedHat
os.release.major:
- 7
- 8
```
=> (SIMP-7709) Improve confinement support

CHANGELOG, Gemfile, lib/puppetx/simp/compliance_mapper.rb, spec/functions/compliance_markup/enforcement_spec.rb
This is a rebase against master of the previous PR since there was a bunch of updates committed that changed the way data was being processed.
---
From original PR: 
Currently, confine is only used in checks specifications, and is applied late in the compile process. This moves it to a function that is applied early in the data compilation process, and also applies it to all relevant data (profiles, controls, checks, and ce).
In addition, this adds missing tests for compliance_markup::enforcement.
=> (SIMP-7813) Allow confinement on data other than checks

lib/puppet/functions/compliance_markup/enforcement.rb, lib/puppetx/simp/compliance_map.rb
This code is loaded by default and is causing issues with the default
puppetserver 5.X load since it starts out with Ruby 1.7, it needs to be
compatible.
SIMP-7823 #close
=> [SIMP-7823] Work around Ruby 1.7 issue

CHANGELOG, README.md, lib/puppetx/simp/compliance_mapper.rb, spec/functions/compliance_markup/00_enforcement_spec.rb, spec/functions/compliance_markup/01_enforcement_confine_spec.rb, spec/functions/compliance_markup/02_enforcement_merge_spec.rb
Prior to this change, hash values were merged using `merge`, causing
unexpected behavior with nested hashes.  This change fixes that by using
`deep_merge!` for hash values.
In addition, this refactors the logic that handles merging to make it
more clear, calls `raise` if there is a type mismatch when merging
(where previously the behavior was undefined), returns less extraneous
data in the Hiera backend, breaks up the
`compliance_markup::enforcement` `lookup()` tests, and adds tests for
merge behavior.
SIMP-7824 #close
=> (SIMP-7824) deep merge hash values

.gitlab-ci.yml, .travis.yml, Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7868 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-compliance_markup
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-compliance_markup
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
=> (SIMP-7848) Add PE2019.8 to pupmod-simp-compliance_markup GL pipeline

CHANGELOG, lib/puppetx/simp/compliance_mapper.rb
Filtering data that would be confined away earlier prevents data that is
unconfined or already passed through confinement from being unexpectedly
confined away.
Also, ignore undefined ces when correlating checks and profiles.
SIMP-8345 #close
=> (SIMP-8345) Apply confinement before merging values

CHANGELOG, lib/puppetx/simp/compliance_mapper.rb, spec/acceptance/nodesets/centos.yml, spec/functions/compliance_markup/00_enforcement_spec.rb, spec/functions/compliance_markup/01_enforcement_confine_spec.rb, spec/functions/compliance_markup/02_enforcement_merge_spec.rb, spec/functions/compliance_markup/03_enforcement_profile_merge_spec.rb, spec/functions/compliance_markup/10_enforce_spec.rb
* Add tests for profile merging
* Deduplicate profile, control, ce, and check names in enforcement tests
to avoid cross-contamination of test data
* Remove useless loops in list_puppet_params function
* Fix calls to deep_merge!
* Fix logic for merging oval-ids, controls, and identifiers
* Add begin/rescue blocks around merges to avoid problems with incorrect
data
SIMP-8375 #close
=> (SIMP-8375) Fix profile merging

CHANGELOG, lib/puppetx/simp/compliance_mapper.rb, metadata.json, spec/functions/compliance_markup/04_enforcement_profile_merge_spec.rb
- Add missing `nil` check when merging controls, identifiers, and oval-ids
- Add `warn` and `debug` in outer `begin` block to avoid silent failures
SIMP-8654 #close
=> (SIMP-8654) Add missing check for nil

spec/functions/compliance_markup/00_enforcement_spec.rb
There is code in compliance_markup that allows a profile to directly reference checks.  This adds a test to validate this behavior.
SIMP-9146 #close
=> (SIMP-9146) Add a test for profiles directly referencing checks

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_manual.yml, .github/workflows/pr_tests.yml, .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9292] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-compliance_markup
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-compliance_markup
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
=> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-compliance_markup

CHANGELOG, lib/puppetx/simp/compliance_mapper.rb, metadata.json
While testing the auditd module with a complex parameter, a bug surfaced in
compliance enforcement where the value would not be discovered in the context
cache.
This is due to the wrong cache being called based on two lines being missed
during the last code update.
While the previous code worked for simple data types, the more complex data
types appear to get lost for unknown reasons.
SIMP-9278 #comment fix compliance enforcement
=> (SIMP-9278) Fix compliance enforcement

CHANGELOG, README.md, lib/puppetx/simp/compliance_mapper.rb, spec/functions/compliance_markup/06_enforcement_debug_spec.rb
Add `compliance_markup::debug::compliance_data` key that dumps compiled input data to the Hiera backend
[SIMP-9791] #close
[SIMP-9791]: https://simp-project.atlassian.net/browse/SIMP-9791
=> (SIMP-9791) Add debug key to dump compiled data

spec/acceptance/nodesets/centos.yml, spec/acceptance/nodesets/oel.yml
- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
- update oel to use generic instead of onyxpoint box
SIMP-10204 #comment update compliance_markup
SIMP-10212 #close
=> (SIMP-10204) Ensure testing with CentOS 8.4
